### ISSUE TITLE
Giving help

### ISSUE THREAD

**Issue by Elsopeen** [xana43/CodeLyoko-Legacy#3]
Hello, I recently (like yesterday) started to update the CortexModders CodeLyokoMod and just found your update, and I'm willing to help you, as there's a lot of stuff I don't really get in the old forge, so contact me if you're still up to work on this

**Comment by xana43** [comment]
Hello, I'm still up to work on this, any contributions will be greatly appriciated

**Comment by Elsopeen** [comment]
I've tried to use your code, and asked for some help on the officials Forge Forums, but as they're not supporting 1.12.2 anymore, I've started the 1.15.2 porting. As everything's different, I can't even reuse some of your code...

**Comment by xana43** [comment]
well, maybe try and port it on a different branch, here, I'll make one for an experimental 1.15 branch (and maybe I should also try to change my work flow to 1.15)

**Comment by Elsopeen** [comment]
I'd be happy to push a branch on this repo, but you'd have to give me the right ^^
By the way, I already recreated some of the surface territory blocks, the dimensions and the tower as a randomly popping structure. Still have a lot of work to do to match your amount of work, but as everything's different :/

**Comment by xana43** [comment]
I have no idea how to give you permission, you might just have to make pull requests

**Comment by xana43** [comment]
nevermind, you've been invited to be a contributor

**Comment by xana43** [comment]
should I continue with the 1.15.2 branch that I'm currently using(while trying to in a way merge your changes) or should I start helping on your branch?

**Comment by Elsopeen** [comment]
As a lot changed from 1.12 to 1.15, I think it would be better to take mine as everything's done with the new version!
Btw, here's my Discord so we can stop using this system to discuss : Elsopéen#1150
